# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: '2'
services:
  bmo.test:
    image: mozillabteam/bmo:test
    command: demo
    volumes:
      - bmo-data-dir:/app/data
    environment:
      - PORT=80
      - LOCALCONFIG_ENV=1
      - BMO_db_host=bmodb
      - BMO_db_name=bugs
      - BMO_db_user=bugs
      - BMO_db_pass=bugs
      - BMO_memcached_namespace=bugzilla
      - BMO_memcached_servers=memcached:11211
      - BZ_QA_ANSWERS_FILE=/app/.circleci/checksetup_answers.txt
    depends_on:
      - bmodb
      - memcached

  phabricator:
    image: mozilla/phabext
    environment:
      - MYSQL_HOST=phabdb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - PHABRICATOR_URI=http://phabricator.test/
      - PHABRICATOR_CDN_URI=http://phabricator.test/
      - BUGZILLA_URL=http://bmo.test
      - BUGZILLA_AUTOMATION_USER=phab-bot@bmo.tld
      - BUGZILLA_AUTOMATION_API_KEY=8G4ly8JkxbypZgh5XrdiHWExVEjPq5S3HvMBll1K

    restart: on-failure
    depends_on:
      - phabdb

  phabricator.test:
    image: nginx:alpine
    volumes:
      - ./docker/phabricator/site.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - phabricator
    depends_on:
      - phabricator
      - tinyproxy

  bmodb:
    image: mozillabteam/bmo-mysql:5.6
    volumes:
      - bmo-mysql-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=bugs
      - MYSQL_USER=bugs
      - MYSQL_PASSWORD=bugs
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  memcached:
    image: memcached:latest

  phabdb:
    image: mysql:5.5
    volumes:
      - phabricator-mysql-db:/var/lib/mysql
      - ./docker/phabricator/mysql:/etc/mysql/conf.d:ro
      - ./docker/phabricator/demo.sql.gz:/docker-entrypoint-initdb.d/demo.sql.gz
    environment:
      - MYSQL_ROOT_PASSWORD=password

  tinyproxy:
    build:
      context: docker/tinyproxy
      dockerfile: ./Dockerfile
    ports:
      - "1090:1090"

volumes:
  phabricator-mysql-db:
  bmo-mysql-db:
  bmo-data-dir:
